import {
  Box,
  Button,
  CircularProgress,
  IconButton,
  LinearProgress,
  MenuItem,
  Select,
  SelectChangeEvent,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import Head from "next/head";
import Editor from "@monaco-editor/react";
import React, { useState } from "react";

import { FaPlay, FaTimes } from "react-icons/fa";
import { runCode } from "../service/api";
import { ApiResponse, LanguageOption } from "../interface/api";

const languages: LanguageOption[] = [
  { title: "Python3", value: "python", compileValue: "python3" },
  { title: "Javascript", value: "javascript", compileValue: "nodejs" },
  { title: "C", value: "c" },
  { title: "C++", value: "cpp" },
  { title: "Java", value: "java" },
];
const theme = [
  { title: "Dark", value: "vs-dark" },
  { title: "Light", value: "light" },
];

let selectedLanguage: LanguageOption = languages[0];

export default function Home() {
  const [config, setConfig] = useState({ language: selectedLanguage.value });
  const [loading, setLoading] = useState(false);
  const [code, setCode] = useState("");
  const [userInput, setUserInput] = useState("");
  const [apiResponse, setApiResponse] = useState<ApiResponse>({
    statusCode: 2,
  });

  // const handleChange = (e: SelectChangeEvent) => {
  //   const { name, value } = e.target;
  //   name && value && setConfig((val) => ({ ...val, [name]: value }));
  // };

  // const handleLanguage = (e: SelectChangeEvent) => {
  //   const { name, value } = e.target;
  //   if (name) {
  //     const obj = languages[Number(value)];
  //     setConfig((val) => ({ ...val, [name]: obj.value }));
  //     selectedLanguage = obj;
  //   }
  // };

  const submit = () => {
    setLoading(true);
    const language = selectedLanguage.compileValue || selectedLanguage.value;
    runCode({
      script: code,
      language: language,
      stdin: userInput,
    })
      .then((resp) => {
        setApiResponse({ ...resp });
      })
      .catch((e) => {
        const response: ApiResponse = {
          statusCode: 400,
          error: "Failed to compile code",
          ...e?.response?.data,
        };
        setApiResponse({ ...response });
      })
      .finally(() => {
        setLoading(false);
      });
  };

  return (
    <Box>
      <Head>
        <title>React Editor </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={"0.5em"} height={"100vh"} p={"1em"} minHeight="500px">
        <Box flexGrow={1}>
          <Stack
            direction={{ xs: "column", sm: "row" }}
            alignItems={"center"}
            gap={"2vw"}
            position="relative"
            // minHeight={"800px"}
            height="100%"
          >
            <Stack
              justifyContent={"center"}
              alignItems="center"
              width="100%"
              height="100%"
              bgcolor="#eee"
              p={1}
            >
              <Typography fontSize={"0.9em"}>
                Write a python program to display hello using python
              </Typography>
            </Stack>
            <Stack width="100%" height="100%">
              <Box flexGrow={1}>
                <Editor
                  height="100%"
                  defaultValue="#some comment"
                  {...config}
                  onChange={(value) => setCode(`${value}`)}
                />
              </Box>
              <Stack direction="row" alignItems={"center"} gap="1vw">
                <Box flexGrow={1}>
                  <TextField
                    fullWidth
                    size="small"
                    placeholder="Type your program input ...."
                    multiline
                    name="userinput"
                    value={userInput}
                    minRows={1}
                    InputProps={{
                      endAdornment: (
                        <>
                          {userInput.length ? (
                            <IconButton
                              color="primary"
                              onClick={() => setUserInput("")}
                            >
                              <FaTimes fontSize={"0.8em"} />
                            </IconButton>
                          ) : null}
                        </>
                      ),
                    }}
                    onChange={(e) => setUserInput(e.target.value)}
                  />
                </Box>
                <Box>
                  <Button
                    variant="outlined"
                    disabled={loading}
                    onClick={submit}
                  >
                    {loading ? (
                      <CircularProgress size={"2em"} variant="indeterminate" />
                    ) : (
                      <Typography> Run </Typography>
                    )}
                  </Button>
                </Box>
                <Box>
                  <Button variant="outlined"> Debug </Button>
                </Box>
              </Stack>
            </Stack>

            {/* <Box>
            <IconButton disabled={loading} onClick={submit}>
              {loading ? (
                <CircularProgress variant="indeterminate" />
              ) : (
                <FaPlay />
              )}
            </IconButton>
          </Box> */}
          </Stack>
        </Box>
        <Box>
          <Stack
            border="0.01em solid black"
            p={"0.2em"}
            // height={"10vh"}
            minHeight="50px"
            mb={2}
            rowGap={"0.2em"}
          >
            <Typography fontWeight="600" fontSize={"0.8em"}>
              Output
            </Typography>
            <Box flexGrow={1}>
              {loading ? (
                <LinearProgress
                  sx={{
                    height: "0.1em",
                  }}
                  variant="indeterminate"
                />
              ) : (
                <Box>
                  <Typography
                    style={{
                      whiteSpace: "pre-line",
                      // color: apiResponse.error ? "red" : "inherit",
                    }}
                  >
                    {apiResponse?.output || apiResponse?.error}
                  </Typography>
                </Box>
              )}
            </Box>
          </Stack>
        </Box>
      </Stack>
    </Box>
  );
}
